### ISSUE TITLE
User can view tech stacks

### ISSUE THREAD

**Issue by ShaAnder** [ShaAnder/elevate_hackathon_2024#3]
As a **user** I can/want to **see the available tech stacks to choose from** so that **I can hone my skills in a specific language**

**Acceptance Criteria:**

- User can navigate to a questions page
- User can see the available tech stacks on the question page ordered 
- user can search for the tech stack of choice
- user can click on the tech stack to view questions

**Tasks:**

- [ ] Implement question page
- [ ] Populate page with lists of tech stack categories
- [ ] make tech stacks clickable for user to navigate to the tech stacks question / answer page
