### ISSUE TITLE
Tech stack pages

### ISSUE THREAD

**Issue by ShaAnder** [ShaAnder/elevate_hackathon_2024#34]
As a **user** I can **see an information page about a language** so that **i can have good resources to ready myself for an interview**

**Acceptance Criteria:**

- Creation of a page for each tech stack we're supporting
- Tech stack should have an image, information about the stack resource links and questions
- user should be able to click through questions and click the resource links

**Tasks:**

- [ ] Create a templates page for the tech stacks
- [ ] link relevant data for imprinting on the page
- [ ] populate the questions on the tech stack page
